<?php
/**
 * @file
 * Provide example help for the advanced help module.
 */

/**
 * Implements hook_menu().
 */
function help_example_menu() {
  // View help topic index.
  $items['admin/help_example'] = [
    'title' => 'Example help',
    'page callback' => 'help_example_index_page',
    'access arguments' => ['view advanced help index'],
    'weight' => 9,
  ];
  return $items;
}

/**
 * Help topic index.
 */
function help_example_index_page() {
  $output = theme('advanced_help_topic', [
    'module' => 'help_example',
    'topic' => 'about-php',
  ]);
  $output .= '&nbsp;' . t('Click the help icon to view some example help about the PHP programming language (from wikipedia.org). Be sure to run cron to update the index if you want to try out the search features.');
  return $output;
}
