<?php

/**
 * @file
 * Functionality for search of Admin Toolbar.
 */

use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;

/**
 * Implements hook_toolbar_alter().
 */
function admin_toolbar_search_toolbar_alter(&$items) {
  $access = \Drupal::currentUser()->hasPermission('use admin toolbar search');
  $admin_toolbar_tools_enabled = \Drupal::service('module_handler')
    ->moduleExists('admin_toolbar_tools');

  $items['administration_search'] = [
    "#type" => "toolbar_item",
    '#access' => $access,
    'tab' => [
      '#type' => 'link',
      '#title' => new TranslatableMarkup('Search'),
      '#url' => URL::fromRoute('system.admin'),
      '#attributes' => [
        'class' => [
          'toolbar-icon',
        ],
      ],
    ],
    'tray' => [
      'search' => [
        '#title' => 'Search',
        '#type' => 'textfield',
        '#size' => 60,
        '#attributes' => [
          'id' => 'admin-toolbar-search-input',
          'aria-labelledby' => 'toolbar-item-administration-search',
        ],
      ],
    ],
    '#attached' => [
      'library' => [
        'admin_toolbar_search/search',
      ],
      'drupalSettings' => [
        'adminToolbarSearch' => [
          'loadExtraLinks' => $admin_toolbar_tools_enabled,
        ],
      ],
    ],
    '#wrapper_attributes' => [
      'id' => 'admin-toolbar-search-tab',
    ],
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

}
